Ssi improvements
ajansen-tub/pyomac pull request #4
Opened 2021-10-05 12:45 UTC by runlevel0

Liebe Mitstreiter:innen, (@ajansen-tub , @somo1212 , @jamysommer )

ich habe die SSI reimplementiert.
Ihr könnt euch das mal anschauen. In den Docs gibt es jetzt einen extra Abschnitt dazu (`ssi.ipynb`).

@ajansen-tub : wenns passt, kannst du mal das in den main branch mergen.
Was die nächsten Schritte sind:
1) Clustering implementieren (bin schon dran)
2) test auf die neuimplementierung umschreiben
3) alte implementierung in Rente schicken?

Gruß,
Patrick

2021-10-08 08:41 UTC, ajansen-tub requested changes
Hallo Patrick, super! Ich habe natürlich schon wider länger nichts gemacht :-( ich würde sagen, dass wir die alte implementierung dann komplett rausschmeißen. Die Reihenfolge der Methoden würde ich vielleicht umstellen, sodass quasi der 'entry point' oben in der Datei ist. Die Filterung bin ich jetzt noch nicht ganz durchstiegen, sieht ansonsten alles solide aus! wäre es ok, wenn du vielleicht noch die Variablen und Funktionen alle in Kleinschreibung setzt (PEP 8)? Ich würde erst danach mergen. Viele Grüße, Andi

2021-10-08 08:41 UTC, ajansen-tub commented on pyomac/ssi.py
> +    assert type(data) == np.ndarray, "numpy array expected"
Den Block sollten wir perspektivisch für alle OMA-Methoden auslager

2021-10-08 08:41 UTC, ajansen-tub commented on pyomac/ssi.py
>  def ssi_cov(data: np.ndarray, fs: float, ts: float = 5., eps_fn: float = 0.02, eps_zeta: float = 0.05,
Ich denke, die ganze alte Methode kann dann weg

2021-10-08 08:41 UTC, ajansen-tub commented on pyomac/ssi.py
> +    R = np.zeros([n_channels, n_channels, n_block_rows * 2], dtype=data.dtype)
ich denke, wir sollten möglichst PEP 8 - Standard einhalten und Variablen und Funktionen ausschliesslich klein schreiben, mit '_' anstatt CamelCasing

2021-10-08 08:41 UTC, ajansen-tub commented on pyomac/ssi.py
> +    # Eigenvalues in continuous time:
continuous time? angular frequency?

2021-10-14 05:25 UTC, runlevel0 commented on pyomac/ssi.py
> +    assert type(data) == np.ndarray, "numpy array expected"
Gute Idee mit generalisierten sanity checks.

2021-10-14 05:26 UTC, runlevel0 commented on pyomac/ssi.py
>  def ssi_cov(data: np.ndarray, fs: float, ts: float = 5., eps_fn: float = 0.02, eps_zeta: float = 0.05,
Ich denke auch. Ich würde die alte methode erst raus nehmen, wenn clustering + tests funktionieren.

2021-10-14 08:38 UTC, runlevel0 commented on pyomac/ssi.py
> +    R = np.zeros([n_channels, n_channels, n_block_rows * 2], dtype=data.dtype)
Auf jeden Fall. Habe nur die `jBlockRows` gefunden. Hast du was anderes noch gefunden? Oder meinst du die Variablen, die für Matrizen stehen?

2021-10-14 11:19 UTC, ajansen-tub commented on pyomac/ssi.py
> +    R = np.zeros([n_channels, n_channels, n_block_rows * 2], dtype=data.dtype)
hey, ja ich meinte auch die matrizen und die funktion '_modal_ID_...'

2021-10-14 11:20 UTC, ajansen-tub commented on pyomac/ssi.py
>  def ssi_cov(data: np.ndarray, fs: float, ts: float = 5., eps_fn: float = 0.02, eps_zeta: float = 0.05,
ok

2021-10-14 11:22 UTC, merged